import pygame
from os.path import join
from os import walk

WINDOW_WIDTH, WINDOW_HEIGHT = 1600, 900
TILE_SIZE = 16

ROOM_COUNT = 50

# scale camera
CAMERA_WIDTH = WINDOW_WIDTH // 2   # 2x zoom
CAMERA_HEIGHT = WINDOW_HEIGHT // 2
CAMERA_ZOOM = 1.25 

ENEMY_HEALTH = 3
ENEMY_DAMAGE = 1
PLAYER_DAMAGE = 1
PLAYER_HEALTH = 5

MAX_ENEMY_COUNT = 30

MAX_TURRET_COUNT = 5


# money 
STARTING_MONEY = 100
TURRET_COST = 25
WALL_COST = 50
TRAP_COST = 100
ENEMY_KILL_MONEY_REWARD = 1

# custom font
FONT_PATH = join('font', 'ScienceGothic.ttf')